const router = require('express').Router()
const { signUp, signIn, sendRequest, acceptRequest, cancelRequest, unFriend, getFriends, createPost, addComment, getPost } = require('../controller/authController')
const { createChat, allChats, getChat } = require('../controller/chatController')
const { sendMessage, allMessages, updateLast } = require('../controller/messageController')
const check = require('../guard/validation')
const upload = require('../utilies/multer')
router.post('/signup'  ,  signUp)
router.post('/signin', signIn)
router.post('/sendrequest', check.isLogin ,sendRequest)
router.post('/acceptrequest' , check.isLogin , acceptRequest)
router.post('/cancelrequest' , check.isLogin , cancelRequest)
router.post('/unfriend', check.isLogin, unFriend)
router.get('/friends', check.isLogin , getFriends)
router.post('/post' , upload.Multer.single('file'), createPost)
router.post('/addcomment' , check.isLogin ,addComment)
router.get('/posts',  check.isLogin , getPost)
router.post('/createchat' , check.isLogin , createChat)
router.get('/allchats' , check.isLogin , allChats)
router.get('/getchat' , check.isLogin,getChat)
router.post('/sendmessage' , check.isLogin , sendMessage)
router.get('/allmessages' , check.isLogin , allMessages)
router.post('/updatelast' , check.isLogin ,updateLast )
module.exports = router;
